# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title      : Dig4Bio-workshops # The title of the book. Will be placed in the left navbar.
author     : Adem R.N. Aouichaoui, Carina L. Gargalo and Fiammetta Caccavale # The author of the book
copyright  : "2024"  # Copyright year to be placed in the footer
logo       : media/logo/dig4bio_logo.png # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/arnaou/dig4bio-workshops  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  use_multitoc_numbering: false

  #######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)
